name: Main Branch Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
jobs:
  ci-step:
    uses: hpatel3747/reusable-workflows/.github/workflows/ci-main.yaml@main
    with:
      componentName: catalogue
#